apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-sa-read-pods
  namespace: gitops-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-read-pods
subjects:
  - kind: ServiceAccount
    name: demo-sa
    namespace: gitops-demo
